export const EMAIL_INPUT = "EMAIL_INPUT";
export const EMAIL_INPUT_BLUR = "EMAIL_INPUT_BLUR";
export const PASSWORD_INPUT = "PASSWORD_INPUT";
export const PASSWORD_INPUT_BLUR = "PASSWORD_INPUT_BLUR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_INPUTS = "RESET_INPUTS";
export const CHECK_FORM_VALIDITY = "CHECK_FORM_VALIDITY";
